/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#e6e0e9',
        'primary-container': '#6750a4',
        'error': '#ffb4ab',
        'on-tertiary-container': '#503d00',
        'on-background': '#e6e0e9',
        'surface-bright': '#3b383e',
        'secondary-container': '#4d4465',
        'background': '#141218',
        'secondary': '#cdc0e9',
        'inverse-surface': '#e6e0e9',
        'on-secondary-container': '#bfb2da',
        'surface-container': '#211f24',
        'error-container': '#93000a',
        'surface-variant': '#36343a',
        'surface-container-highest': '#36343a',
        'outline-variant': '#494551',
        // Mode-switchable accent — updated via CSS vars on :root
        'tertiary': 'var(--color-tertiary, #e7c365)',
        'tertiary-container': 'var(--color-tertiary-container, #c9a74d)',
        'on-tertiary': 'var(--color-on-tertiary, #3e2e00)',
        'on-surface-variant': '#cbc4d2',
        'inverse-on-surface': '#322f35',
        'on-tertiary-fixed': '#241a00',
        'on-secondary': '#342b4b',
        'on-primary': '#381e72',
        'surface-dim': '#141218',
        'primary': '#cfbcff',
        'surface': '#141218',
        'outline': '#948e9c',
        'surface-container-low': '#1d1b20',
        'surface-container-high': '#2b292f',
        'surface-container-lowest': '#0f0d13',
        'on-primary-container': '#e0d2ff',
        'inverse-primary': '#6750a4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        'input-padding': '12px',
        'margin-page': '24px',
        'card-padding': '20px',
        'gutter-grid': '16px',
      },
      fontFamily: {
        'subheader-label': ['Hanken Grotesk', 'sans-serif'],
        'app-title': ['Space Grotesk', 'sans-serif'],
        'body-main': ['Hanken Grotesk', 'sans-serif'],
        'body-main-mobile': ['Hanken Grotesk', 'sans-serif'],
        'display-header': ['Noto Serif', 'serif'],
      },
      fontSize: {
        'subheader-label': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '500' }],
        'app-title': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-main': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-main-mobile': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-header': ['22px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
