# Generated by Django 6.0.6 on 2026-06-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=600)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
