# Generated by Django 6.0.6 on 2026-06-15 16:54

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('spins', '0003_draft'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='storyelement',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
